eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
server:
    port: ${SERVER_PORT:7070}
spring:
    application:
        name: ${APP_NAME:NOTIFICATION-SERVICE}
