eureka:
    client:
        fetch-registry: ${EUREKA_FETCH:false}
        register-with-eureka: ${EUREKA_REGISTER:false}
logging:
    file:
        path: eureka.log
    pattern:
        level:
            org:
                cb: DEBUG
                cb.booking: ERROR
                springframework: DEBUG
server:
    port: ${SERVER_PORT:8761}
spring:
    application:
        name: ${APP_NAME:BOOKING-EUREKA-SERVER}
