eureka:
    client:
        service-url:
            defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
server:
    port: ${SERVER_PORT:8080}
spring:
    application:
        name: ${APP_NAME:BOOKING-SERVICE}
    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/bookingservice?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate:
          ddl-auto: create
        show-sql: true

management:
    endpoints:
        web:
            exposure:
                exclude: "*"
