#=====================================
# Server Config
#=====================================
server:
  port: ${SERVER_PORT:8080}

#========================================================
#Eureka Config
#========================================================
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}

#=========================================================
# Application Config
#=========================================================
spring:
    application:
        name: ${APP_NAME:BOOKING-SERVICE}

#==========================================================
# Database Config
#==========================================================
    datasource:
#        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://host.docker.internal:3306/bookingservice?createDatabaseIfNotExist=true
        username: root
        password: root
    jpa:
        hibernate:
          ddl-auto: create
        show-sql: true
#===================================================================================
# Actuator Config
#===================================================================================
management:
  endpoints:
    web:
      exposure:
        include: "*"
#  health:
#    livenessstate:
#      enabled: true
#    readinessstate:
#      enabled: true
#  endpoint:
#    health:
#      probes:
#        enabled: true
