version: '3.8'
services:
  eureka-server:
    build: ./booking-eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    healthcheck:
      test: "curl --fail --silent localhost:8761/actuator/health/readiness | grep UP || exit 0"
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    environment:
      - SERVER_PORT=8761
      - APP_NAME=BOOKING-EUREKA-SERVER
      - EUREKA_FETCH=false
      - EUREKA_REGISTER=false
  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - APP_NAME=BOOKING-SERVICE
      - EUREKA_URL=http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_healthy
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - APP_NAME=PAYMENT-SERVICE
      - EUREKA_URL=http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_healthy
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "7070:7070"
    environment:
      - SERVER_PORT=7070
      - APP_NAME=NOTIFICATION-SERVICE
      - EUREKA_URL=http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_healthy
  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "80:80"
    environment:
      - SERVER_PORT=80
      - APP_NAME=API-GATEWAY
      - EUREKA_URL=http://eureka-server:8761/eureka
    depends_on:
      eureka-server:
        condition: service_healthy