version: '3.8'
services:
  eureka-server:
    build: ./booking-eureka-server
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - APP_NAME=BOOKING-EUREKA-SERVER
      - EUREKA_FETCH=false
      - EUREKA_REGISTER=false
  booking-service:
    build: ./booking-service
    container_name: booking-service
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - APP_NAME=BOOKING-SERVICE
      - EUREKA_URL=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
  payment-service:
    build: ./payment-service
    container_name: payment-service
    ports:
      - "9090:9090"
    environment:
      - SERVER_PORT=9090
      - APP_NAME=PAYMENT-SERVICE
      - EUREKA_URL=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server
  notification-service:
    build: ./notification-service
    container_name: notification-service
    ports:
      - "7070:7070"
    environment:
      - SERVER_PORT=7070
      - APP_NAME=NOTIFICATION-SERVICE
      - EUREKA_URL=http://eureka-server:8761/eureka
    depends_on:
      - eureka-server