#Server Config

server:
  port: ${SERVER-PORT:80}
#APP Name
spring:
  application:
    name: ${APP_NAME:API-GATEWAY}
#gateway Config
  cloud:
    gateway:
      routes:
        - id: BOOKING-SERVICE-ID
          uri: lb://BOOKING-SERVICE
          predicates:
            - Path=/api/booking/**

#Eureka Config
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
